### ISSUE TITLE
Unable to install due to tools/refactor/lexical dependency missing 

### ISSUE THREAD

**Issue by MarkMoudy** [isaiah/unexport#1]
Looks like the dependency package `golang.org/x/tools/refactor/lexical` has been removed and is no longer go get-able.  See this [commit](https://github.com/golang/tools/commit/e21b7325f78e5114b2601c053c3421d1aafae058) from 3 days ago.  

Maybe vendoring in the dependency would be a good fix?

**Comment by gonzaloserrano** [comment]
+1

**Comment by isaiah** [comment]
Vendored, will make a proper fix later.

**Comment by ghost** [comment]
here is the CL mentioned in the commit:

- https://go-review.googlesource.com/c/tools/+/9544
- https://github.com/golang/tools/commit/03e05ec5a59d9f211a842c8ab4cc709058ac69d1
